apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-php
  template:
    metadata:
      labels:
        app: api-php
    spec:
      containers:
      - name: api-php-container
        image: mi-aplicacion-php:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-php-service
spec:
  selector:
    app: api-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
